[package]
name = "cotar-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cotar"
path = "src/main.rs"

[dependencies]
cotar = { path="../cotar" }
clap = { version = "3.0.14", features = ["derive"] }
tar = { version="0.4.0" }