name: Release
on:
  push:
    branches:
      - master

jobs:

  release_please:
    name: Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      cli_release_created: ${{steps.release.outputs['cotar-cli--release_created']}}
      cli_tag_name: ${{steps.release.outputs['cotar-cli--tag_name']}}
      release_created: ${{ steps.release.outputs['cotar-cli--release_created'] || steps.release.outputs['cotar--release_created'] }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: rust
          command: manifest

  # Build sources for every OS
  github_build:
    name: Build CLI release binaries
    needs: release_please
    if: ${{ needs.release_please.outputs.cli_release_created == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: cotar-x86_64-unknown-linux-gnu.tar.gz
          - target: arm-unknown-linux-musleabihf
            os: ubuntu-latest
            name: cotar-arm-unknown-linux-musleabihf.tar.gz
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: Build | Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.target }}
          use-cross: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Post Build | Prepare artifacts 
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../${{ matrix.name }} cotar
          cd -

      - name: Release | Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  upload_artifacts:
    name: Add CLI Build Artifacts to Release
    needs: [release_please, github_build]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Adding assets require permissions
    steps:
      - name: Setup | Artifacts
        uses: actions/download-artifact@v3

      - name: Setup | Checksums
        run: for file in cotar-*/cotar-*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Setup | Publish Release
        run: |
          gh release upload ${{ needs.release_please.outputs.cli_tag_name }} cotar-*/cotar* --repo=blacha/cotar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
